### PR TITLE
route file for js integration

### PR DESCRIPTION
**Pull request by waxzce**
Hi
this cinfiguration is design for complex javavascript componement or css import

some js import scripts and the actual configuration fails.

with this, it works

### CODE REVIEW

**Comment by orefalo** [comment]
Could you provide more details.. what do you mean by "complex js components" ?

**Comment by waxzce** [comment]
Sure

When you work with some JS component like aloha text editor it dynamically link some js file from the path where it is provide. But the path is changing with press and the js component doesn't find the others files. This configuration provides the capacity of find the file ;-)

**Comment by orefalo** [comment]
interesting, from your pull it looks like you are only adding a few simple routes. I am myself facing a related issue: I've been playing with greenscript lately, any experience with it ?

**Comment by waxzce** [comment]
yes I only add this lines.

About greenscript : I used it, but in don't use today. I use press instead.

**Pull request closed without merging**
